### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by herzogkienast** [web-vision/wv_deepltranslate#180] opened 2023-04-15 15:06 UTC
The extension ignores <br> - so half wraps. I have tested in deepl itself. So deepl can handle br. Would be great to handle it in the extension too.
Thanks in advance.
Andrea

**Comment by calien666** [comment] 2023-05-05 08:48
@herzogkienast 
I'm trying to understand your issue. Please could you provide more information on this?
What would you do?
What is the expected result?
What is the current result?
Which version of wv_deepltranslate do you use?

**Comment by herzogkienast** [comment] 2023-05-05 09:14
@calien666 
Thank you for your reply. 
I'm using version 2.3.1
For example: I have a List of ingredients, like:

2 Zucchini
1 Zitrone
Ollivenöl
Salz, Pfeffer

In my bodytext I use a half brake (shift return) what results <br /> in HTML. So the whole <p> looks like this:
<p>2 Zucchini<br />
4 Eigelb<br />
160g Weißwein<br />
100g Parmesan<br />
1/2. Bd Schnittlauch<br />
1 Zitrone<br />
Ollivenöl<br />
Salz, Pfeffer</p>

While translating <br /> is ignored and all the ingedients will be shown in one line.
I want to have the <br /> also in the translated stuff :).

**Comment by calien666** [comment] 2023-05-05 09:21
Thank you for your detailed answer. Please take a deep breath and wait, as the issue is fixed in current master. We had the issue in #65 and fixed it. The next release will respect your HMTL tags.

**Closed by calien666** 2023-05-05 09:21 UTC
Labels: bug
