### ISSUE TITLE
[BUG] Glossary is created based on the getTwoLetterIsoCode of the highest sys_language which can cause missing or empty glossary upload.

### ISSUE THREAD

**Issue by joey-bolts** [web-vision/wv_deepltranslate#313] opened 2024-01-05 12:38 UTC
**Describe the bug**
I have a glossary for a couple of languages. Our default language is English.
However we have multiple domains based on language, for example

- sys_lang 0 = .com - getTwoLetterIsoCode = en
- sys_lang 5 = .usa - getTwoLetterIsoCode = en
- sys_lang 12 = .ca - getTwoLetterIsoCode = en
- sys_lang 3 = .it - getTwoLetterIsoCode = it

We only have a glossary for lets say language 0 (en) and language 3 (it) 
When pressing glossary sync no en => it or it => en get created. 

**To Reproduce**
Setup languages as above, we the lower language uid has a glossary list but one with an higher id does not. 
(Make sure getTwoLetterIsoCode is the same)

**Expected behavior**
Glossaries should be created

**TYPO3 Setup**
- V10
- Apache
- MySQL
- php 7.4
- DeepL paid Api
- Composer

# Issue and solution
In `Classes/Domain/Repository/GlossaryRepository.php` there should be made a change. 
Something like the following. Since now `$localizationArray[$targetLanguageIsoCode] = $localizedEntries;` actually always overrides the glossary entries from the highest sys_language_uid where getTwoLetterIsoCode matches. This means you could be missing items or overriding the values with an empty array 

```
        // fetch all language information available for building all glossaries
        foreach ($localizationLanguageIds as $localizationLanguageId) {
            $localizedEntries = $this->getLocalizedEntries($pageId, $localizationLanguageId);
            $targetLanguageIsoCode = $this->getTargetLanguageIsoCode($site, $localizationLanguageId);
            $localizationArray[$targetLanguageIsoCode] = $localizedEntries;
        }
```

to

```
        // fetch all language information available for building all glossaries
        foreach ($localizationLanguageIds as $localizationLanguageId) {
            $localizedEntries = $this->getLocalizedEntries($pageId, $localizationLanguageId);
            $targetLanguageIsoCode = $this->getTargetLanguageIsoCode($site, $localizationLanguageId);
            if(!isset($localizationArray[$targetLanguageIsoCode])) {
                $localizationArray[$targetLanguageIsoCode] = [];
            }

            if(!empty($localizedEntries)) {
                $localizationArray[$targetLanguageIsoCode] += $localizedEntries;
            }
        }
```

**Comment by sbuerk** [comment] 2024-05-24 13:56
@bechit thank you for creating this issue. Sadly, even changing
the code on our side would not lead to the expected result.

The  **DeepL API Docs** clearly mentioning a concrete list of two
letter language codes for glossaries source and target languages,
and not the local codes containing the region (US, GB, ...). [[1]](https://developers.deepl.com/docs/v/de/api-reference/glossaries)

This is also emphasized in the open-api document for the glossary
endpoints [[2]](https://developers.deepl.com/docs/v/de/api-reference/glossaries/openapi-spec-for-glossary-management).

Here the supported list of language keys:

* DA (Danish)
* DE (German)
* EN (English)
* ES (Spanish)
* FR (French)
* IT (Italian)
* JA (Japanese)
* KO (Korean)
* NB (Norwegian Bokmål)
* NL (Dutch)
* PL (Polish)
* PT (Portuguese)
* RU (Russian)
* SV (Swedish)
* ZH (Chinese)

That means, even if we would switch to use the full locale, it does
not work as `en_US` is literally not supported - or `US` (country code).

Just for completness, there is a dedicated endpoint retrieving the list
of supported languages [[3]](https://developers.deepl.com/docs/v/de/api-reference/languages), which is only valid for the translate api calls.
It contains a handfull locales containing the country part.

```terminal
curl -X GET 'https://api.deepl.com/v2/languages?type=target' \
--header 'Authorization: DeepL-Auth-Key [yourAuthKey]'
```

returns

```json
[
  {
    "language": "BG",
    "name": "Bulgarian",
    "supports_formality": false
  },
  {
    "language": "CS",
    "name": "Czech",
    "supports_formality": false
  },
  {
    "language": "DA",
    "name": "Danish",
    "supports_formality": false
  },
  {
    "language": "DE",
    "name": "German",
    "supports_formality": true
  },
  {
    "language": "EL",
    "name": "Greek",
    "supports_formality": false
  },
  {
    "language": "EN-GB",
    "name": "English (British)",
    "supports_formality": false
  },
  {
    "language": "EN-US",
    "name": "English (American)",
    "supports_formality": false
  },
  {
    "language": "ES",
    "name": "Spanish",
    "supports_formality": true
  },
  {
    "language": "ET",
    "name": "Estonian",
    "supports_formality": false
  },
  {
    "language": "FI",
    "name": "Finnish",
    "supports_formality": false
  },
  {
    "language": "FR",
    "name": "French",
    "supports_formality": true
  },
  {
    "language": "HU",
    "name": "Hungarian",
    "supports_formality": false
  },
  {
    "language": "ID",
    "name": "Indonesian",
    "supports_formality": false
  },
  {
    "language": "IT",
    "name": "Italian",
    "supports_formality": true
  },
  {
    "language": "JA",
    "name": "Japanese",
    "supports_formality": true
  },
  {
    "language": "KO",
    "name": "Korean",
    "supports_formality": false
  },
  {
    "language": "LT",
    "name": "Lithuanian",
    "supports_formality": false
  },
  {
    "language": "LV",
    "name": "Latvian",
    "supports_formality": false
  },
  {
    "language": "NB",
    "name": "Norwegian",
    "supports_formality": false
  },
  {
    "language": "NL",
    "name": "Dutch",
    "supports_formality": true
  },
  {
    "language": "PL",
    "name": "Polish",
    "supports_formality": true
  },
  {
    "language": "PT-BR",
    "name": "Portuguese (Brazilian)",
    "supports_formality": true
  },
  {
    "language": "PT-PT",
    "name": "Portuguese (European)",
    "supports_formality": true
  },
  {
    "language": "RO",
    "name": "Romanian",
    "supports_formality": false
  },
  {
    "language": "RU",
    "name": "Russian",
    "supports_formality": true
  },
  {
    "language": "SK",
    "name": "Slovak",
    "supports_formality": false
  },
  {
    "language": "SL",
    "name": "Slovenian",
    "supports_formality": false
  },
  {
    "language": "SV",
    "name": "Swedish",
    "supports_formality": false
  },
  {
    "language": "TR",
    "name": "Turkish",
    "supports_formality": false
  },
  {
    "language": "UK",
    "name": "Ukrainian",
    "supports_formality": false
  },
  {
    "language": "ZH",
    "name": "Chinese (simplified)",
    "supports_formality": false
  }
]
```

Again, the OpenApi docs stats allowed language keys for source and target
language for the translation endpoints, which differs slightly [[4]](https://developers.deepl.com/docs/v/de/api-reference/translate/openapi-spec-for-text-translation):

**SOURCE**

* BG
* CS
* DA
* DE
* EL
* EN
* ES
* ET
* FI
* FR
* HU
* ID
* IT
* JA
* KO
* LT
* LV
* NB
* NL
* PL
* PT
* RO
* RU
* SK
* SL
* SV
* TR
* UK
* ZH

**TARGET**

* BG
* CS
* DA
* DE
* EL
* EN-GB
* EN-US
* ES
* ET
* FI
* FR
* HU
* ID
* IT
* JA
* KO
* LT
* LV
* NB
* NL
* PL
* PT-BR
* PT-PT
* RO
* RU
* SK
* SL
* SV
* TR
* UK
* ZH

That allows basically to translate to `en_US` for example. However, back to the glossary
it would use the same glossary (`EN`) for `en_US`, `en_GB. 

We could have a look for the translation point and how to deal there for the translation
target and allow it in that case (if not done already, not checked yet to be honest).

**References**

* [[1] DeepL API Docs: Manage glossaries - https://developers.deepl.com/docs/v/de/api-reference/glossaries](https://developers.deepl.com/docs/v/de/api-reference/glossaries)
* [[2] DeepL OpenApi Spec: Create a glossary - https://developers.deepl.com/docs/v/de/api-reference/glossaries/openapi-spec-for-glossary-management](https://developers.deepl.com/docs/v/de/api-reference/glossaries/openapi-spec-for-glossary-management)
* [[3] DeepL OpenApi Spec: Retrieve languages - https://developers.deepl.com/docs/v/de/api-reference/languages](https://developers.deepl.com/docs/v/de/api-reference/languages)
* [[4] DeepL OpenApi Spec: Request Translation - https://developers.deepl.com/docs/v/de/api-reference/translate/openapi-spec-for-text-translation](https://developers.deepl.com/docs/v/de/api-reference/translate/openapi-spec-for-text-translation)

Note: Going to close this issue now. This is not a bug, the DeepL Api simply does not
support that and thus no action required to be taken. This counts for free and paid API.

**Closed by sbuerk** 2024-05-24 13:56 UTC
Labels: bug
